import { mkdir, writeFile } from "node:fs/promises";
import { basename, resolve } from "node:path";
import {
  extractOperations,
  getBaseUrl,
  getProjectName,
  inputSchemaForOperation,
  loadOpenApiSpec,
} from "./openapi.js";
import type { ApiOperation, GeneratorOptions, JsonSchema, OpenApiSpec } from "./types.js";

export async function generateMcpServer(options: GeneratorOptions): Promise<void> {
  const spec = await loadOpenApiSpec(options.specPath);
  const operations = extractOperations(spec);
  const projectName = options.serverName || getProjectName(spec);
  const baseUrl = getBaseUrl(spec);
  const outDir = resolve(options.outDir);

  await mkdir(`${outDir}/src`, { recursive: true });

  await Promise.all([
    writeFile(`${outDir}/package.json`, packageJson(projectName), "utf8"),
    writeFile(`${outDir}/tsconfig.json`, tsconfigJson(), "utf8"),
    writeFile(`${outDir}/.env.example`, envExample(baseUrl), "utf8"),
    writeFile(`${outDir}/README.md`, readme(spec, projectName, baseUrl, operations), "utf8"),
    writeFile(`${outDir}/src/index.ts`, serverSource(projectName, baseUrl, operations), "utf8"),
  ]);
}

function packageJson(projectName: string): string {
  return `${JSON.stringify(
    {
      name: projectName,
      version: "0.1.0",
      type: "module",
      private: true,
      scripts: {
        build: "tsc",
        start: "node dist/index.js",
        dev: "tsx src/index.ts",
      },
      dependencies: {
        "@modelcontextprotocol/sdk": "^1.13.0",
        zod: "^3.25.56",
      },
      devDependencies: {
        "@types/node": "^22.15.30",
        tsx: "^4.19.4",
        typescript: "^5.8.3",
      },
      engines: {
        node: ">=20",
      },
    },
    null,
    2,
  )}
`;
}

function tsconfigJson(): string {
  return `${JSON.stringify(
    {
      compilerOptions: {
        target: "ES2022",
        module: "NodeNext",
        moduleResolution: "NodeNext",
        strict: true,
        esModuleInterop: true,
        forceConsistentCasingInFileNames: true,
        skipLibCheck: true,
        outDir: "dist",
        rootDir: "src",
      },
      include: ["src/**/*.ts"],
    },
    null,
    2,
  )}
`;
}

function envExample(baseUrl: string): string {
  return `API_BASE_URL=${baseUrl}
# Use either API_BEARER_TOKEN or API_KEY.
API_BEARER_TOKEN=
API_KEY=
API_KEY_HEADER=x-api-key
`;
}

function readme(
  spec: OpenApiSpec,
  projectName: string,
  baseUrl: string,
  operations: ApiOperation[],
): string {
  const title = spec.info?.title || projectName;
  const rows = operations
    .map((operation) => {
      return `| \`${operation.toolName}\` | ${operation.method.toUpperCase()} | \`${operation.path}\` | ${operation.risk} |`;
    })
    .join("\n");

  return `# ${title} MCP Server

Generated by api-to-mcp from \`${basename(projectName)}\`.

## Setup

\`\`\`bash
npm install
cp .env.example .env
npm run build
npm start
\`\`\`

Default base URL: \`${baseUrl}\`

## Tools

| Tool | Method | Path | Risk |
| --- | --- | --- | --- |
${rows}

## Safety Notes

- Read operations are generated from GET, HEAD, and OPTIONS.
- Write operations are generated from POST, PUT, and PATCH.
- Destructive operations are generated from DELETE.
- Review generated tools before exposing them to AI clients.
`;
}

function serverSource(projectName: string, baseUrl: string, operations: ApiOperation[]): string {
  const toolRegistrations = operations.map(toolRegistrationSource).join("\n\n");

  return `import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import { z } from "zod";

const server = new McpServer({
  name: ${JSON.stringify(projectName)},
  version: "0.1.0",
});

const API_BASE_URL = process.env.API_BASE_URL || ${JSON.stringify(baseUrl)};
const API_BEARER_TOKEN = process.env.API_BEARER_TOKEN;
const API_KEY = process.env.API_KEY;
const API_KEY_HEADER = process.env.API_KEY_HEADER || "x-api-key";

type ToolArgs = Record<string, unknown>;

function authHeaders(): Record<string, string> {
  const headers: Record<string, string> = {};

  if (API_BEARER_TOKEN) {
    headers.authorization = \`Bearer \${API_BEARER_TOKEN}\`;
  }

  if (API_KEY) {
    headers[API_KEY_HEADER] = API_KEY;
  }

  return headers;
}

function appendPathParams(pathTemplate: string, args: ToolArgs): string {
  return pathTemplate.replace(/\\{([^}]+)\\}/g, (_match, key: string) => {
    const value = args[key];
    if (value === undefined || value === null) {
      throw new Error(\`Missing required path parameter: \${key}\`);
    }
    return encodeURIComponent(String(value));
  });
}

function appendQueryParams(url: URL, queryParamNames: string[], args: ToolArgs): void {
  for (const name of queryParamNames) {
    const value = args[name];
    if (value === undefined || value === null || value === "") {
      continue;
    }

    if (Array.isArray(value)) {
      for (const item of value) {
        url.searchParams.append(name, String(item));
      }
      continue;
    }

    url.searchParams.set(name, String(value));
  }
}

async function callApi(config: {
  method: string;
  path: string;
  queryParamNames: string[];
  headerParamNames: string[];
  args: ToolArgs;
  body?: unknown;
}) {
  const url = new URL(appendPathParams(config.path, config.args), API_BASE_URL);
  appendQueryParams(url, config.queryParamNames, config.args);

  const headers: Record<string, string> = {
    accept: "application/json",
    ...authHeaders(),
  };

  for (const name of config.headerParamNames) {
    const value = config.args[name];
    if (value !== undefined && value !== null) {
      headers[name] = String(value);
    }
  }

  const init: RequestInit = {
    method: config.method,
    headers,
  };

  if (config.body !== undefined) {
    headers["content-type"] = "application/json";
    init.body = JSON.stringify(config.body);
  }

  const response = await fetch(url, init);
  const contentType = response.headers.get("content-type") || "";
  const payload = contentType.includes("application/json")
    ? await response.json()
    : await response.text();

  if (!response.ok) {
    throw new Error(\`API request failed: \${response.status} \${response.statusText} \${JSON.stringify(payload)}\`);
  }

  return payload;
}

${toolRegistrations}

const transport = new StdioServerTransport();
await server.connect(transport);
`;
}

function toolRegistrationSource(operation: ApiOperation): string {
  const schema = inputSchemaForOperation(operation);
  const queryParamNames = operation.parameters
    .filter((parameter) => parameter.in === "query")
    .map((parameter) => parameter.name);
  const headerParamNames = operation.parameters
    .filter((parameter) => parameter.in === "header")
    .map((parameter) => parameter.name);

  return `server.tool(
  ${JSON.stringify(operation.toolName)},
  ${JSON.stringify(`${operation.summary} Risk: ${operation.risk}.`)},
  ${jsonToZodShape(schema)},
  async (args) => {
    const payload = await callApi({
      method: ${JSON.stringify(operation.method.toUpperCase())},
      path: ${JSON.stringify(operation.path)},
      queryParamNames: ${JSON.stringify(queryParamNames)},
      headerParamNames: ${JSON.stringify(headerParamNames)},
      args,
      body: "body" in args ? args.body : undefined,
    });

    return {
      content: [
        {
          type: "text",
          text: typeof payload === "string" ? payload : JSON.stringify(payload, null, 2),
        },
      ],
    };
  },
);`;
}

function jsonToZodShape(schema: JsonSchema): string {
  const properties = schema.properties || {};
  const required = new Set(schema.required || []);
  const entries = Object.entries(properties).map(([name, property]) => {
    const zod = zodForSchema(property);
    return `  ${JSON.stringify(name)}: ${required.has(name) ? zod : `${zod}.optional()`}`;
  });

  return `{\n${entries.join(",\n")}\n}`;
}

function zodForSchema(schema: JsonSchema): string {
  if (schema.enum?.length) {
    const values = schema.enum.map((item) => JSON.stringify(String(item))).join(", ");
    return `z.enum([${values}] as [string, ...string[]])${description(schema)}`;
  }

  switch (schema.type) {
    case "integer":
    case "number":
      return `z.number()${description(schema)}`;
    case "boolean":
      return `z.boolean()${description(schema)}`;
    case "array":
      return `z.array(${zodForSchema(schema.items || { type: "string" })})${description(schema)}`;
    case "object":
      return `z.record(z.string(), z.unknown())${description(schema)}`;
    default:
      return `z.string()${description(schema)}`;
  }
}

function description(schema: JsonSchema): string {
  return schema.description ? `.describe(${JSON.stringify(schema.description)})` : "";
}
